# Generated by Django 5.1.7 on 2025-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterm', '0003_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_personnel',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
